### PR TITLE
Fix build versioning

### PR DESCRIPTION
**Pull request by kakra**
The current code doesn't properly detect the latest release. This PR fixes that.

### CODE REVIEW

**Comment by rhyst** [comment]
This worked for me, successfully updated updated between 0.7 on master and 0.7 on this branch.

**Comment by kakra** [comment]
> This worked for me, successfully updated updated between 0.7 on master and 0.7 on this branch.

Could you post the console output of the update process, or uninstall/install if you use that, so I can verify some information? I don't have a system using DKMS, so I need some help. :-)

**Comment by rhyst** [comment]
Log from update.sh
[update.log](https://github.com/atar-axis/xpadneo/files/4842120/update.log)

**Comment by kakra** [comment]
@rhyst Perfect! Thanks... Seems to work as intended.

Does the list of installed dkms modules now show `v0.7-37-gb08b43f` for xpadneo?

**Comment by rhyst** [comment]
It does:
```
hid-xpadneo, v0.7-37-gb08b43f, 5.4.0-39-generic, x86_64: installed
```

**Pull request merged**
