### PR TITLE
[NOT FOR MERGE] Modified directional rumble test

### PR DESCRIPTION
**Pull request by kakra**
I modified the rumble test by playing the effects in shorter intervals
and repeating a complete circle multiple times.

It looks like the effect is gone now, I cannot really feel how it walks
from left to right.

Also, directional rumble in Wine joy.cpl doesn't work. But I did not
check if it is not implemented there or uses a different interface.

### CODE REVIEW

**Comment by kakra** [comment]
If you want to test on Wine yourself, you should add my patches from https://github.com/kakra/wine/commits/patches-3.3/xboxcontroller

**Comment by kakra** [comment]
It seems to play rumble on the triggers only the first round.

**Comment by atar-axis** [comment]
Does it work for you the way I mentioned above?

**Comment by kakra** [comment]
I still had no time to test this, I'll do soon.

**Comment by kakra** [comment]
I see you merged my idea of changing the rumble test, so I close this.

**Pull request closed without merging**
