### PR TITLE
Let the user disable FF even partly (only triggers, only main)

### PR DESCRIPTION
**Pull request by atar-axis**

### CODE REVIEW

**Comment by atar-axis** [comment]
@CodeCanna - new parameter, do you want to add it or should I ?

**Comment by CodeCanna** [comment]
Hey there @atar-axis

**Comment by CodeCanna** [comment]
So you added an enable_ff as well? Cool sure I'll add it if you haven't already

**Comment by atar-axis** [comment]
Yeah right, i changed the `disable_ff` behaviour - it is described in hid-xpadneo.c 😊✌

**Comment by CodeCanna** [comment]
Yeah I would be happy to, and I get to check out the hid-xpadneo.c file.  Not too great in C but should be interesting!

**Comment by atar-axis** [comment]
Just push your changes to the enable_ff branch as a PR - i will then merge it :)

**Comment by CodeCanna** [comment]
I have looked in hid-xpadneo.c, I can't seem to find anything regarding the enable_ff.  Can you tell me around where is is in there?

**Comment by atar-axis** [comment]
It isn't called enable_ff but it is still disable_ff, Just the behaviour and valid values are different now ;)

**Comment by CodeCanna** [comment]
Ohhh ok

**Comment by CodeCanna** [comment]
Oh I see, it's no longer a "y" or "n" it's 1 or 0, for the valid values.

**Comment by atar-axis** [comment]
Nearly, Take a Look at Line 46 ;) it is 0 to 3 now :)

**Comment by CodeCanna** [comment]
I'm sorry I don't understand, probably because I'm not too familiar with C.

Line 46:
```MODULE_PARM_DESC(disable_ff, "(bool) Disable all force-feedback effects (rumble). 1: disable ff, 0: enable ff.");```

Isn't disable_ff declared as a `static bool` which means it can only have 2 values true and false?  The description says 1:disable_ff, 0: enable_ff.  But I do see an extra `disable_ff` at the beginning, is that the third option?

**Comment by atar-axis** [comment]
Not anymore ;) https://github.com/atar-axis/xpadneo/blob/enable_ff/hid-xpadneo/src/hid-xpadneo.c

**Comment by CodeCanna** [comment]
Oh was I pulling the wrong version?  Do I need to pull from that branch?  That would explain it XD.

**Comment by atar-axis** [comment]
Yes, you have to! :) It isn't yet merged that's what the pull request is for :)

Just run `git checkout enable_ff` or `git clone <address> -b enable_ff`

**Comment by atar-axis** [comment]
@CodeCanna: Sorry, I had some spare time and wanted to finally close this issue :grin: What do you think about the changes?

**Comment by atar-axis** [comment]
@all: I will merge this PR in 7h if no objections are raised.

**Comment by CodeCanna** [comment]
Oh, cool I haven't looked yet, I just to up XD

**Comment by CodeCanna** [comment]
Yes, that's exactly how I have done it.  That is how I did it, but you beat me to it.  Not too big of a fix.  Very nice.

**Pull request merged**
