### PR TITLE
Add Elite 2 controllers

### PR DESCRIPTION
**Pull request by hibes**
I attempted to add Elite 2 controllers, but I'm having some issues getting it to work.  Any advice on where I might look to try to resolve the issue?

### CODE REVIEW

**Comment by hibes** [comment]
```
[400029.928066] xpadneo: goodbye!
[400088.756104] usb 1-1.1.4.4.4: USB disconnect, device number 38
[400091.784096] hid-generic 0005:045E:0B05.005F: unknown main item tag 0x0
[400091.786927] xpadneo: hello there!
[400117.496003] input: Xbox Elite Wireless Controller as /devices/pci0000:00/0000:00:14.0/usb1/1-14/1-14:1.0/bluetooth/hci0/hci0:256/0005:045E:0B05.005F/input/input200
[400117.496259] input: Xbox Elite Wireless Controller Consumer Control as /devices/pci0000:00/0000:00:14.0/usb1/1-14/1-14:1.0/bluetooth/hci0/hci0:256/0005:045E:0B05.005F/input/input201
[400117.496388] input: Xbox Elite Wireless Controller Keyboard as /devices/pci0000:00/0000:00:14.0/usb1/1-14/1-14:1.0/bluetooth/hci0/hci0:256/0005:045E:0B05.005F/input/input203
[400117.496517] hid-generic 0005:045E:0B05.005F: input,hidraw0: BLUETOOTH HID v9.03 Gamepad [Xbox Elite Wireless Controller] on 5c:80:b6:70:8b:5d
[400122.870035] xpadneo 0005:045E:0B05.005F: unknown main item tag 0x0
[400150.348564] debugfs: Directory '33' with parent 'devices' already present!
[400150.444360] usb 1-1.1.4.4.4: new full-speed USB device number 39 using xhci_hcd
[400150.564707] usb 1-1.1.4.4.4: New USB device found, idVendor=045e, idProduct=0b00, bcdDevice= 4.07
[400150.564712] usb 1-1.1.4.4.4: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[400150.564715] usb 1-1.1.4.4.4: Product: Controller
[400150.564718] usb 1-1.1.4.4.4: Manufacturer: Microsoft
[400150.564720] usb 1-1.1.4.4.4: SerialNumber: 3032363330303330383835393335
[400150.572695] input: Generic X-Box pad as /devices/pci0000:00/0000:00:14.0/usb1/1-1/1-1.1/1-1.1.4/1-1.1.4.4/1-1.1.4.4.4/1-1.1.4.4.4:1.0/input/input205
[400150.767856] input: Xbox Elite Wireless Controller as /devices/pci0000:00/0000:00:14.0/usb1/1-14/1-14:1.0/bluetooth/hci0/hci0:256/0005:045E:0B05.005F/input/input204
[400150.768058] xpadneo 0005:045E:0B05.005F: input,hidraw0: BLUETOOTH HID v9.03 Gamepad [Xbox Elite Wireless Controller] on 5c:80:b6:70:8b:5d
```

**Comment by hibes** [comment]
The controller intermittently works via bluetooth (for like 30s at most), but not at all over USB.

**Comment by atar-axis** [comment]
1. it looks like hid-generic is claiming the device you need to deregister it from it. I am not sure if that worked at your tries
2. xpadneo is a bluetooth driver only 
3. I am quite sure that the HID report descriptor differs from the one for the S version

Unfortunately I do not own an Elite 2 controller, so it's hard to help here

**Comment by duganchen** [comment]
Surely this is redundant with https://github.com/atar-axis/xpadneo/pull/144 ?

**Comment by atar-axis** [comment]
yes, right - i am just not sure which one is still developed by their creators :grin:

**Comment by atar-axis** [comment]
closing this in favor of #144

**Comment by hibes** [comment]
#144 looked abandoned, sorry.

**Pull request closed without merging**
